name: chang_2nd_main_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 # icon
  firebase_core: ^1.20.0 #firebase core
  firebase_auth: ^3.5.0 # auth
  cloud_firestore: ^3.4.0 #cloud_firestore
  provider: ^6.0.2 #provider
  google_fonts: ^2.2.0 #google Fonts
  dotted_line: ^3.1.0 #dotted line
  webview_flutter: ^3.0.4  #webview
  flutter_svg: ^1.0.1
  flutter_svg_provider: ^1.0.3
  google_sign_in: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: SpoqaHanSansNeo
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Bold.ttf
        - asset: assets/fonts/SpoqaHanSansNeo-Light.ttf
        - asset: assets/fonts/SpoqaHanSansNeo-Medium.ttf
        - asset: assets/fonts/SpoqaHanSansNeo-Regular.ttf