name: chang_2nd_main_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 # icon
  firebase_core: ^1.20.0 #firebase core
  firebase_auth: ^3.5.0 # auth
  cloud_firestore: ^3.4.0 #cloud_firestore
  provider: ^6.0.2 #provider
  google_fonts: ^2.2.0 #google Fonts
  dotted_line: ^3.1.0 #dotted line

  geolocator: ^9.0.1  #위치 정보
  webview_flutter_plus: ^0.3.0+2
  webview_flutter: ^3.0.4  #webview
  flutter_svg: ^1.0.1
  flutter_svg_provider: ^1.0.3
  google_sign_in: ^5.4.0
  flutter_spinkit: ^5.1.0
  share_plus: ^4.0.10
  yaml: ^3.1.1
  firebase_analytics: ^9.3.0
  flutter_launcher_icons: ^0.10.0
  intl: ^0.17.0
  flutter_localizations: 
    sdk: flutter
  localization: ^2.1.0
  rxdart: ^0.27.5
  flutter_local_notifications: ^9.8.0+1
  sign_in_with_apple: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/ref/
    - pubspec.yaml
  fonts:
    - family: SpoqaHanSansNeo
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Bold.ttf
        - asset: assets/fonts/SpoqaHanSansNeo-Light.ttf
        - asset: assets/fonts/SpoqaHanSansNeo-Medium.ttf
        - asset: assets/fonts/SpoqaHanSansNeo-Regular.ttf
