name: chang_2nd_main_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 # icon
  firebase_core: ^1.10.6 #firebase core
  firebase_auth: ^3.3.4 # auth
  cloud_firestore: ^3.1.4 #cloud_firestore
  provider: ^6.0.2 #provider
  google_fonts: ^2.2.0 #google Fonts
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SpoqaHanSansNeo
      fonts:
        - asset: fonts/SpoqaHanSansNeo-Bold.ttf
        - asset: fonts/SpoqaHanSansNeo-Light.ttf
        - asset: fonts/SpoqaHanSansNeo-Medium.ttf
        - asset: fonts/SpoqaHanSansNeo-Regular.ttf
        - asset: fonts/SpoqaHanSansNeo-Thin.ttf
          style: italic